from abc import ABC, abstractmethod


class PaymentProvider(ABC):
    @abstractmethod
    def initialize_payment(self,*,amount_minor:int,email:str,reference:str,callback_url:str,metadata:dict): ...
    @abstractmethod
    def verify_payment(self,reference:str): ...
    @abstractmethod
    def refund_payment(self,reference:str,amount_minor:int|None=None): ...
    @abstractmethod
    def verify_webhook(self,raw_body:bytes,signature:str)->bool: ...
